/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BricoJavaInfraTools;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        String classUnderTest = "azerty";
        assertTrue("someLibraryMethod should return 'true'", (classUnderTest.length() > 0));
    }
}
